discourse_reactions:
  discourse_reactions_enabled:
    default: false
    client: true
  discourse_reactions_like_icon:
    client: true
    default: "heart"
  discourse_reactions_reaction_for_like:
    client: true
    type: enum
    default: "heart"
    enum: ReactionForLikeSiteSettingEnum
  discourse_reactions_enabled_reactions:
    type: emoji_list
    default: thumbsup|laughing|open_mouth|clap|confetti_ball|hugs
    client: true
  discourse_reactions_desaturated_reaction_panel:
    default: false
    client: true
